version: '3.8'

# TODO: Add environment variables
# Mongo Port
# MONGO_INITDB_ROOT_PASSWORD
# ME_CONFIG_MONGODB_ADMINPASSWORD
# Mongo Express Port

# Add auth for mongo-express (currently admin/pass)

services:  
  # Mongo DB
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword    
    volumes:
      - ./data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"      

  # Database Manager
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secretpassword  
      - ME_CONFIG_MONGODB_PORT=27017
    links:
      - mongo