version: '3'

services:  
  # Mongo DB
  mongo:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secretpassword    
    volumes:
      - /usr/data/db
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"      

  # Nest.js API
  app:
    build:
      context: ./api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/library
    volumes:
        - ./api:/usr/src/app
        - /usr/src/app/node_modules

  # Database Manager Web Interface
  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secretpassword  
      - ME_CONFIG_MONGODB_PORT=27017
    links:
      - mongo
